Histogram with filters
CartoDB/cra-template-carto pull request #60
Opened 2020-11-06 11:04 UTC by Josmorsot

Model is WIP by @alasarr

2020-11-06 11:05 UTC, Josmorsot commented
I've added an additional histogram as example. I have to remove it before merge

2020-11-11 13:34 UTC, alasarr requested changes

2020-11-11 13:34 UTC, alasarr commented on template/src/lib/sdk/widgets/HistogramWidget.js
> +        return { left: ticks[i - 1], right: ticks[i] };
Instead of left and right. Can we replace it with an array?

2020-11-11 13:34 UTC, alasarr commented on template/src/lib/sdk/widgets/HistogramWidget.js
> +      const indexes = bars.map((b) => parseInt(b.replace('cat_', '')));
I don't like the way of getting the index from the string. What about if we just return the index of the bar?

2020-11-11 20:56 UTC, alasarr approved these changes

2020-11-11 20:57 UTC, merged